server {
    listen 8080;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    access_log /dev/stdout;
    error_log /dev/stderr warn;

    location = /logs {
        return 301 /logs/;
    }

    location /logs/ {
        try_files $uri $uri/ /logs/index.html;
        add_header Cache-Control "no-store, no-cache, must-revalidate";
    }

    location / {
        try_files $uri $uri/ /index.html;
        add_header Cache-Control "no-store, no-cache, must-revalidate";
    }
}
